# Generated by Django 3.2.12 on 2023-04-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('lust_name', models.CharField(max_length=127)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Выпусники',
                'verbose_name_plural': 'Выпусников',
            },
        ),
    ]
