# Generated by Django 3.2.12 on 2023-04-26 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_graduate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Graduate',
        ),
        migrations.AlterField(
            model_name='clas',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claases', to='mainapp.school'),
        ),
        migrations.AlterField(
            model_name='student',
            name='clas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='mainapp.clas'),
        ),
    ]
